apiVersion: v2
# renovate: github=oliver006/redis_exporter
appVersion: v1.90.0
description: Prometheus exporter for Redis metrics
name: prometheus-redis-exporter
version: 6.30.1
home: https://github.com/oliver006/redis_exporter
sources:
  - https://github.com/oliver006/redis_exporter
icon: https://cncf-icons.com/artwork/projects/prometheus/icon/color/prometheus-icon-color.svg
keywords:
  - prometheus
  - redis
maintainers:
  - name: acondrat
    email: arcadie.condrat@gmail.com
    url: https://github.com/acondrat
  - name: zanhsieh
    email: zanhsieh@gmail.com
    url: https://github.com/zanhsieh
type: application
