suite: test prometheus-operator clusterrole
templates:
  - prometheus-operator/clusterrole.yaml
tests:
  - it: should grant patch and update on managed resource finalizers
    asserts:
      - contains:
          path: rules
          content:
            apiGroups:
              - monitoring.coreos.com
            resources:
              - alertmanagers
              - alertmanagers/finalizers
              - prometheusagents
              - prometheusagents/finalizers
              - prometheuses
              - prometheuses/finalizers
              - thanosrulers
              - thanosrulers/finalizers
            verbs:
              - patch
      - contains:
          path: rules
          content:
            apiGroups:
              - monitoring.coreos.com
            resources:
              - alertmanagers/finalizers
              - prometheusagents/finalizers
              - prometheuses/finalizers
              - thanosrulers/finalizers
            verbs:
              - update
