{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prom-label-proxy.fullname" . }}
  namespace: {{ template "prom-label-proxy.namespace" . }}
  labels:
    {{- include "prom-label-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prom-label-proxy.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}