---
suite: PrometheusRule runbook_url annotations

templates:
  - prometheus/rules-1.14/*.yaml

excludeTemplates:
  - prometheus/rules-1.14/*rules*.yaml

tests:
  - it: should render runbook_url annotation in PrometheusRule files
    asserts:
      - exists:
          path: spec.groups[*].rules[*].annotations.runbook_url