name: Chart Feature Request
description: Suggest an improvement to a Helm chart
title: "[name of the chart e.g. prometheus-couchdb-exporter] Issue Title"
labels: [enhancement]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: chart-name
    attributes:
      label: Which chart?
      description: Select the chart this feature request is related to.

      options:
        - alertmanager
        - alertmanager-snmp-notifier
        - jiralert
        - kube-prometheus-stack
        - kube-state-metrics
        - prom-label-proxy
        - prometheus
        - prometheus-adapter
        - prometheus-blackbox-exporter
        - prometheus-cloudwatch-exporter
        - prometheus-conntrack-stats-exporter
        - prometheus-consul-exporter
        - prometheus-couchdb-exporter
        - prometheus-druid-exporter
        - prometheus-elasticsearch-exporter
        - prometheus-fastly-exporter
        - prometheus-ipmi-exporter
        - prometheus-json-exporter
        - prometheus-kafka-exporter
        - prometheus-memcached-exporter
        - prometheus-modbus-exporter
        - prometheus-mongodb-exporter
        - prometheus-mysql-exporter
        - prometheus-nats-exporter
        - prometheus-nginx-exporter
        - prometheus-node-exporter
        - prometheus-operator-admission-webhook
        - prometheus-operator-crds
        - prometheus-pgbouncer-exporter
        - prometheus-pingdom-exporter
        - prometheus-pingmesh-exporter
        - prometheus-postgres-exporter
        - prometheus-pushgateway
        - prometheus-rabbitmq-exporter
        - prometheus-redis-exporter
        - prometheus-smartctl-exporter
        - prometheus-snmp-exporter
        - prometheus-sql-exporter
        - prometheus-stackdriver-exporter
        - prometheus-statsd-exporter
        - prometheus-systemd-exporter
        - prometheus-to-sd
        - prometheus-windows-exporter
        - prometheus-yet-another-cloudwatch-exporter
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Is your feature request related to a problem ?
      description: Give a clear and concise description of what the problem is.
      placeholder: ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: prop-solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered. If nothing, please enter `NONE`
    validations:
      required: true

  - type: textarea
    id: additional-ctxt
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
