{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "yet-another-cloudwatch-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yet-another-cloudwatch-exporter.labels" . | nindent 4 }}
spec:
{{- toYaml (omit .Values.podDisruptionBudget "enabled") | nindent 2 }}
  selector:
    matchLabels:
      {{- include "yet-another-cloudwatch-exporter.selectorLabels" . | nindent 8 }}
{{- end }}
