kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      #language=yaml
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        failSwapOn: false
        memorySwap:
          swapBehavior: LimitedSwap

  - role: worker
    kubeadmConfigPatches:
      #language=yaml
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        failSwapOn: false
        memorySwap:
          swapBehavior: LimitedSwap

  - role: worker
    kubeadmConfigPatches:
      #language=yaml
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        failSwapOn: false
        memorySwap:
          swapBehavior: LimitedSwap
