alertmanager:
  alertmanagerSpec:
    replicas: 2
  ingress:
    enabled: true
    hosts:
      - "*.example.com"
  route:
    main:
      enabled: true
      hostnames:
        - "*.example.com"
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: my-header-name
                value: my-new-header-value
      additionalRules:
        - filters:
            - type: RequestHeaderModifier
              requestHeaderModifier:
                set:
                  - name: my-header-name
                    value: my-new-header-value
          matches:
            - path:
                type: PathPrefix
                value: /foo/
  servicePerReplica:
    enabled: true
  routePerReplica:
    enabled: true
    hostPrefix: alertmanager
    hostDomain: example.com
    parentRefs:
      - name: gateway
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          set:
            - name: my-header-name
              value: my-new-header-value


prometheus:
  prometheusSpec:
    replicas: 2
  ingress:
    enabled: true
    hosts:
      - "*.example.com"
  route:
    main:
      enabled: true
      hostnames:
        - "*.example.com"
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: my-header-name
                value: my-new-header-value
      additionalRules:
        - filters:
            - type: RequestHeaderModifier
              requestHeaderModifier:
                set:
                  - name: my-header-name
                    value: my-new-header-value
          matches:
            - path:
                type: PathPrefix
                value: /foo/
  servicePerReplica:
    enabled: true
  routePerReplica:
    enabled: true
    hostPrefix: prometheus
    hostDomain: example.com
    parentRefs:
      - name: gateway
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          set:
            - name: my-header-name
              value: my-new-header-value

thanosRuler:
  ingress:
    enabled: true
    hosts:
      - "*.example.com"
  route:
    main:
      enabled: true
      hostnames:
        - "*.example.com"
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: my-header-name
                value: my-new-header-value
      additionalRules:
        - filters:
            - type: RequestHeaderModifier
              requestHeaderModifier:
                set:
                  - name: my-header-name
                    value: my-new-header-value
          matches:
            - path:
                type: PathPrefix
                value: /foo/
