myDomain: tpl.com

serviceMonitor:
  enabled: true
  targets:
  - name: example-tpl
    url: http://example.{{ .Values.myDomain }}/healthz
  - name: example-non-tpl
    url: http://example.non-tpl.com/healthz
