{{- if and .Values.prometheus.enabled .Values.prometheus.gatewayAPI.httpRoute.enabled -}}
  {{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- with .Values.prometheus.gatewayAPI.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $serviceName }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    {{- with .Values.prometheus.gatewayAPI.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.prometheus.gatewayAPI.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.prometheus.gatewayAPI.httpRoute.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $serviceName }}
          port: {{ .Values.prometheus.service.port }}
      {{- with .Values.prometheus.gatewayAPI.httpRoute.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.gatewayAPI.httpRoute.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
