{{- if and .Values.prometheus.enabled .Values.prometheus.serviceAccount.create .Values.prometheus.serviceAccount.createTokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-prometheus-stack.prometheus.tokenSecretName" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    app.kubernetes.io/name: {{ template "kube-prometheus-stack.name" . }}-prometheus
    app.kubernetes.io/component: prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ template "kube-prometheus-stack.prometheus.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
