collectors: []
extraArgs:
  - --custom-resource-state-only=true
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: apiextensions.k8s.io
            version: v1
            kind: CustomResourceDefinition
          metricNamePrefix: ksm_ci_crd
          metrics:
            - name: info
              help: Info metric for CustomResourceDefinition objects.
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
