prometheus:
  monitor:
    enabled: true
    additionalLabels:
      release: prometheus
    jobLabel: app.kubernetes.io/name
    targetLabels:
      - app.kubernetes.io/name
    http:
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: kube_pod_status_phase
          action: keep
