suite: test statefulset
templates:
  - statefulset.yaml
tests:
  - it: persistentVolumeClaim contain apiVersion and kind
    set:
      persistence.enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - exists:
          path: spec.volumeClaimTemplates[0].apiVersion
      - exists:
          path: spec.volumeClaimTemplates[0].kind
