#!/usr/bin/env bash
# Auto-generate .github/advanced-issue-labeler.yml from chart directories.
cat <<HEADER
# This file is auto-generated by scripts/generate-labeler.sh. Do not edit manually.

policy:
  - template: [bug_report.yml, feature_request.yml]
    section:
      - id: [chart-name]
        label:
HEADER

for chart in $(find charts/ -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort); do
  cat <<CHARTS
          - name: "chart/${chart}"
            keys: ["${chart}"]
CHARTS
done
