suite: deployment
templates:
  - deployment.yaml
tests:
  - it: probes /status
    asserts:
      - equal:
          path: spec.template.spec.containers[0].livenessProbe.httpGet.path
          value: /status
      - equal:
          path: spec.template.spec.containers[0].readinessProbe.httpGet.path
          value: /status
