{{- if .Values.podMonitor.enabled }}
apiVersion: {{ .Values.podMonitor.apiVersion | default "monitoring.coreos.com/v1" }}
kind: PodMonitor
metadata:
{{- if .Values.podMonitor.labels }}
  labels:
    {{- include "prometheus-postgres-exporter.labels" . | nindent 4 }}
{{ toYaml .Values.podMonitor.labels | indent 4}}
{{- end }}
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  namespace: {{ .Values.podMonitor.namespace | default (include "prometheus-postgres-exporter.namespace" .) | quote }}
spec:
  podMetricsEndpoints:
  - port: http
{{- if .Values.podMonitor.interval }}
    interval: {{ .Values.podMonitor.interval }}
{{- end }}
{{- if .Values.podMonitor.telemetryPath }}
    path: {{ .Values.podMonitor.telemetryPath }}
{{- end }}
{{- if .Values.podMonitor.scheme }}
    scheme: {{ .Values.podMonitor.scheme }}
{{- end }}
{{- if .Values.podMonitor.timeout }}
    scrapeTimeout: {{ .Values.podMonitor.timeout }}
{{- end }}
{{- if .Values.podMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.podMonitor.metricRelabelings | indent 4 }}
{{- end }}
{{- if .Values.podMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.podMonitor.relabelings | nindent 4 }}
{{- end }}
{{- with .Values.podMonitor.tlsConfig }}
    tlsConfig:
{{- toYaml . | nindent 6 }}
{{- end }}
  jobLabel: {{ template "prometheus-postgres-exporter.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ include "prometheus-postgres-exporter.namespace" . | quote }}
  selector:
    matchLabels:
      {{- include "prometheus-postgres-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
