{{- if not (or .Values.config.datasource.passwordSecret .Values.config.datasourceSecret .Values.config.datasource.passwordFile ) -}}
{{ $_ := required "config.datasource.password is required when not using config.datasource.passwordSecret, config.datasource.passwordFile, or config.datasourceSecret" .Values.config.datasource.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  namespace: {{ include "prometheus-postgres-exporter.namespace" . }}
  labels:
    {{- include "prometheus-postgres-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  data_source_password: {{ tpl .Values.config.datasource.password . | b64enc }}
{{- end -}}
