---
## Test case: multiple httproutes
route:
  http:
    enabled: true
    apiVersion: "gateway.networking.k8s.io/v1"
    parentRefs:
      - name: gateway-1
        namespace: gateway-1
        sectionName: http
    hostnames:
      - alertmanager.example.com
    matches:
      - path:
          type: PathPrefix
          value: /
    httpsRedirect: true
  https:
    enabled: true
    apiVersion: "gateway.networking.k8s.io/v1"
    parentRefs:
      - name: gateway-1
        namespace: gateway-1
        sectionName: https
    hostnames:
      - alertmanager.example.com
    matches:
      - path:
          type: PathPrefix
          value: /
