---
name: Stale
permissions: {}

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mark stale pull requests
        uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          stale-pr-label: lifecycle/stale
          exempt-pr-labels: lifecycle/frozen
          operations-per-run: 50
          days-before-stale: 90
          days-before-close: -1
          days-before-issue-stale: -1
          days-before-issue-close: -1
          remove-stale-when-updated: true
          stale-pr-message: 'This pull request has been marked as stale due to no activity for 90 days. The label will be removed automatically when new activity occurs.'
