permissions: {}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'

jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'false'
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'true'
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
