permissions: {}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
      - 'changelog/index.html'

jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
          cp -f changelog/index.html ${{ runner.temp }}/index.html
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          mkdir -p changelog
          cp -f ${{ runner.temp }}/index.html changelog/index.html
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md changelog/index.html
          git commit --signoff -m "Sync from main"
          git push
